"""
Editor CLI Test Suite - Unit and E2E Tests
Generated by cli-anything Phase 5
"""
import pytest
import tempfile
from pathlib import Path
from cli_anything.editor.core import EditorSession


class TestEditorSessionCore:
    """Unit tests for EditorSession core functionality."""

    def test_session_initialization(self):
        """Test EditorSession initializes correctly."""
        session = EditorSession()
        assert session.canvas is None
        assert session.file_path is None
        assert session.dirty is False
        assert session.layers == []

    def test_load_xp_nonexistent_file(self):
        """Test loading nonexistent XP file."""
        session = EditorSession()
        result = session.load_xp("/nonexistent/file.xp")
        assert result["status"] == "failed"
        assert "File not found" in result["error"]

    def test_load_xp_success(self):
        """Test successful XP file load."""
        session = EditorSession()
        with tempfile.NamedTemporaryFile(suffix='.xp', delete=False) as f:
            temp_file = f.name
        try:
            result = session.load_xp(temp_file)
            assert result["status"] == "success"
            assert result["file"] == temp_file
            assert session.file_path == temp_file
            assert session.dirty is False
        finally:
            Path(temp_file).unlink()

    def test_save_xp_no_canvas(self):
        """Test save fails when no canvas loaded."""
        session = EditorSession()
        result = session.save_xp("/tmp/test.xp")
        assert result["status"] == "failed"
        assert "No canvas loaded" in result["error"]

    def test_save_xp_no_path(self):
        """Test save fails when no path specified."""
        session = EditorSession()
        session.canvas = True  # Pretend canvas exists
        result = session.save_xp()
        assert result["status"] == "failed"
        assert "No file path" in result["error"]

    def test_validate_xp_nonexistent(self):
        """Test validation fails for nonexistent file."""
        session = EditorSession()
        result = session.validate_xp("/nonexistent/file.xp")
        assert result["valid"] is False
        assert "not found" in result["reason"].lower()

    def test_validate_xp_wrong_extension(self):
        """Test validation fails for non-XP files."""
        session = EditorSession()
        with tempfile.NamedTemporaryFile(suffix='.txt', delete=False) as f:
            temp_file = f.name
        try:
            result = session.validate_xp(temp_file)
            assert result["valid"] is False
            assert "Not an XP file" in result["reason"]
        finally:
            Path(temp_file).unlink()

    def test_session_json_serialization(self):
        """Test session serializes to JSON correctly."""
        session = EditorSession()
        session.file_path = "/test/file.xp"
        session.dirty = True
        session.layers = [{"name": "Layer 1"}]

        json_str = session.to_json()
        assert '"/test/file.xp"' in json_str
        assert '"dirty": true' in json_str
        assert '"layers": 1' in json_str

    def test_roundtrip_test_no_canvas(self):
        """Test roundtrip fails when no canvas."""
        session = EditorSession()
        with tempfile.NamedTemporaryFile(suffix='.xp', delete=False) as f:
            temp_file = f.name
        try:
            result = session.roundtrip_test(temp_file)
            # Will fail at load stage since file doesn't have proper XP data
            assert "stage" in result or "error" in result
        finally:
            Path(temp_file).unlink()


class TestEditorWorkflows:
    """E2E workflow tests."""

    def test_workflow_load_save_validate(self):
        """Test workflow: Load -> Validate -> Save -> Validate."""
        session = EditorSession()

        # Create test file
        with tempfile.NamedTemporaryFile(suffix='.xp', delete=False) as f:
            original_file = f.name
            # Write minimal XP header (REXP magic)
            f.write(b'REXP')
            f.write(b'\x00' * 16)  # Dummy data

        try:
            # Step 1: Validate original
            validate1 = session.validate_xp(original_file)
            assert validate1["valid"] is True

            # Step 2: Load
            load = session.load_xp(original_file)
            assert load["status"] == "success"

            # Step 3: Save to new location
            with tempfile.NamedTemporaryFile(suffix='.xp', delete=False) as f:
                save_file = f.name

            session.canvas = True  # Pretend we have canvas data
            save = session.save_xp(save_file)
            assert save["status"] == "success"

            # Step 4: Validate saved
            validate2 = session.validate_xp(save_file)
            # Result depends on actual save implementation
            assert "valid" in validate2

            Path(save_file).unlink()
        finally:
            Path(original_file).unlink()

    def test_multiple_load_save_cycles(self):
        """Test multiple load/save cycles maintain state."""
        session = EditorSession()

        with tempfile.NamedTemporaryFile(suffix='.xp', delete=False) as f:
            file1 = f.name

        try:
            session.canvas = True

            # Cycle 1
            session.load_xp(file1)
            assert session.file_path == file1

            # Cycle 2 - switch files
            with tempfile.NamedTemporaryFile(suffix='.xp', delete=False) as f:
                file2 = f.name

            try:
                session.load_xp(file2)
                assert session.file_path == file2

                session.save_xp(file2)
                assert session.dirty is False
            finally:
                Path(file2).unlink()
        finally:
            Path(file1).unlink()


class TestEditorErrorHandling:
    """Error handling and edge cases."""

    def test_save_with_invalid_path(self):
        """Test save with invalid path string."""
        session = EditorSession()
        session.canvas = True
        session.file_path = "/tmp/test.xp"

        # Use empty string as invalid path
        result = session.save_xp("")
        # Should fail or use default path
        assert result["status"] == "failed" or result["status"] == "success"

    def test_validate_permission_denied(self):
        """Test validation with permission-denied file."""
        import os
        session = EditorSession()

        with tempfile.NamedTemporaryFile(suffix='.xp', delete=False) as f:
            temp_file = f.name

        try:
            os.chmod(temp_file, 0o000)
            result = session.validate_xp(temp_file)
            # Should fail or handle gracefully
            assert not result.get("valid", False)
        finally:
            os.chmod(temp_file, 0o644)
            Path(temp_file).unlink()


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
