name = "xpedit-router"
main = "xpedit-router.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "rikiworld.com/xpedit", zone_name = "rikiworld.com" },
  { pattern = "rikiworld.com/xpedit/*", zone_name = "rikiworld.com" },
]

[vars]
CLOUD_RUN_URL = "https://asciicker-xpedit-6abo3pnlfa-uc.a.run.app"
